/* ============================================================
   FOODWISE AI · 11-copilot.js
   AI Module 12 — FoodWise Copilot. Local rule-based assistant
   that answers from live application state (demo mode).
   ============================================================ */
const CQ = ['How much food did we waste this month?', 'Why did waste increase?', 'What should we prepare tomorrow?', "Which food item is most at risk?", 'Which NGO should receive this surplus?', 'How much CO₂ did we save?', 'Which storage unit has abnormal temperature?', 'What is our biggest source of waste?', 'Why did we save food today?'];
function toggleCopilot(open) {
    const c = $('#copilot'); const o = open === undefined ? !c.classList.contains('open') : open; c.classList.toggle('open', o);
    if (o && !S.copilotLog.length) { copPush('ai', `<div class="ans">✦ FoodWise Copilot</div>I can see your live operational data — forecasts, inventory risk, NGO matches, IoT sensors and impact. Ask me anything, or try a suggestion below.<div class="sup demo-note">Local demo reasoning over app state · no external LLM configured.</div>`); renderChips() }
}
function renderChips() { $('#copChips').innerHTML = CQ.map(q => `<button class="chipq" onclick="copAsk('${q.replace(/'/g, "\\'")}')">${q}</button>`).join('') }
function copPush(who, html) { S.copilotLog.push({ who, html }); const m = $('#copMsgs'); m.insertAdjacentHTML('beforeend', `<div class="msg ${who}">${html}</div>`); m.scrollTop = m.scrollHeight }
function copSend() { const i = $('#copInput'); if (!i.value.trim()) return; copAsk(i.value.trim()); i.value = '' }
function copAsk(q) {
    toggleCopilot(true); copPush('user', q); $('#copChips').innerHTML = '';
    const a = copilotAnswer(q); setTimeout(() => { copPush('ai', a); renderChips(); const m = $('#copMsgs'); m.scrollTop = m.scrollHeight }, 500)
}
function copilotAnswer(q) {
    ql = q.toLowerCase(); const I = S.impact;
    if (/save.*today|why.*save/.test(ql)) {
        if (S.demoDelta) return `<div class="ans">Today you saved food through a full AI chain.</div>
      1️⃣ Forecast: AI predicted <b>920 meals</b> (94% confidence) and recommended 940. 2️⃣ <b>60 meals</b> of surplus still emerged — FoodVision verified quality GOOD. 3️⃣ Shelf-life model gave a 4-hour window, so AI matched <b>Helping Hands Foundation (96%)</b> and cut the route 18.2 → 13.9 km. 4️⃣ <b>58 meals delivered</b>.
      <div class="sup">≈ ${S.demoDelta.kg} kg food · ~${Math.round(S.demoDelta.co2)} kg CO₂e avoided (est.) · ${S.demoDelta.water} L water (est.) · ${INR(S.demoDelta.money)} saved (est.)</div>
      <div class="rec">Prevention worked too: the 940-meal plan avoided ~80 meals of potential overproduction before cooking even started.</div>`;
        return `<div class="ans">No redistribution completed yet today.</div>Run the AI Demo to watch the full predict → redistribute → measure chain, or check the inventory page for at-risk batches you can redirect now.<div class="sup">Demo data only.</div>`
    }
    if (/waste.*month|how much.*waste/.test(ql)) return `<div class="ans">This month: <b>512 kg</b> of food waste across 4 kitchens — down 9% vs last month.</div><div class="sup">Biggest source: overproduction (61%), then spoilage (22%). Campus Kitchen contributes 48% of the total. Waste trend fell in 6 of the last 10 days after production-plan recommendations were accepted.</div><div class="rec">Accepting the rice-production cut takes ~6 kg/day out of the forecast — see Surplus & Waste.</div>`;
    if (/why.*waste.*increase|increase/.test(ql)) return `<div class="ans">Food waste increased <b>14%</b> last week.</div>The main contributor was overproduction during three low-attendance days (a schedule change wasn't reflected in the production plan).<div class="sup">Attribution: overproduction +18% on Tue/Thu/Sat · spoilage flat · plate waste flat.</div><div class="rec">Demand forecasting can reduce the expected waste by approximately <b>22 kg next week</b> — accept the pending production recommendation.</div>`;
    if (/prepare|tomorrow.*cook|production/.test(ql)) { const f = S.f7[0]; return `<div class="ans">Prepare <b>${AI.demand(0).rec} meals</b> for tomorrow (${f.d}).</div>AI predicts demand of <b>${f.v} meals</b> at ${f.c}% confidence (band ${N(AI.demand(0).lo)}–${N(AI.demand(0).hi)}). The recommendation adds a 2% service buffer → expected surplus ≈ 20 meals, expected waste &lt; 5.<div class="sup">Drivers: Tuesday effect 38% · attendance 27% · events 17% · weather 12%.</div><div class="rec">Send the plan from the Demand Forecast page — one click updates the kitchen display.</div>` }
    if (/risk|at risk|expir/.test(ql)) { const it = S.inv[0]; return `<div class="ans">Most at risk: <b>${it.name} (${it.id})</b> — ${riskBadge(it.risk)}</div>${it.q} ${it.u} left, shelf life <b class="mono">${Math.max(0, Math.round((it.ts - now()) / 36e5))} h</b>, draw rate ${it.rate}.<div class="sup">AI insight: ${it.note}</div><div class="rec">Redistribute it now — the match engine already ranks Helping Hands Foundation at 96%.</div>` }
    if (/ngo|surplus.*receiv|donat/.test(ql)) { const n = S.ngos[0]; return `<div class="ans">Best recipient: <b>${n.name}</b> — match score <b>${n.score}%</b>.</div>2.4 km away, capacity ${n.cap} meals, veg-compatible, pickup available, ${n.rel}% reliability.<div class="sup">Score = distance 27 + capacity 22 + compatibility 18 + urgency 12 + availability 9 + reliability 8.</div><div class="rec">Open Redistribution to dispatch with an optimized 13.9 km route (−23.6%).</div>` }
    if (/co2|carbon|environment|water/.test(ql)) return `<div class="ans">Estimated CO₂e avoided: <b>${I.co2T} tonnes</b> over 90 days.${S.demoDelta ? ` That includes ~${Math.round(S.demoDelta.co2)} kg from today's redistribution.` : ''}</div><div class="sup">1,240+ kg food saved × 2.26 kg CO₂e/kg · water ≈ ${N(I.waterL)} L · cost ≈ ${INR(I.money)} (all Estimated Impact, demo data).</div><div class="rec">The full methodology is open on the Impact & ESG page — plus a downloadable report.</div>`;
    if (/temperature|storage unit|abnormal|sensor|iot/.test(ql)) { const b = S.sensors[1]; return `<div class="ans">${S.iotAlerted && !S.coldBFixed ? `<b>Cold Storage B is abnormal — ${b.temp.toFixed(1)} °C</b>, above the 2–6 °C safe band.` : `All storage units are within safe bands right now.`}</div>${S.iotAlerted && !S.coldBFixed ? 'AI raised a quality-deterioration risk alert; batches should move to Cold Storage A.' : 'Cold A 4.2 °C · Cold B stable · Dry 23.6 °C · Freezer −18.3 °C.'}<div class="sup">Simulated MQTT stream · anomaly detection on temperature/humidity/gas.</div><div class="rec">Watch it live on the IoT Storage page — the demo drifts Cold Storage B into an alert every visit.</div>` }
    if (/biggest source|source of waste/.test(ql)) return `<div class="ans">Your biggest source of waste is <b>overproduction — 61%</b>.</div><div class="sup">Breakdown: overproduction 61% · spoilage/storage 22% · plate waste 11% · processing loss 6%.</div><div class="rec">That's exactly what the surplus predictor targets: prepare less, earlier — before waste exists.</div>`;
    if (/hello|hi |help|what can/.test(ql)) return `<div class="ans">I'm the FoodWise Copilot.</div>I answer from your live data: demand, surplus, waste attribution, inventory risk, NGO matching, routes, IoT anomalies and impact.<div class="sup">Try: "What should we prepare tomorrow?" or "Why did we save food today?"</div>`;
    return `<div class="ans">I couldn't map that to the demo knowledge base.</div>I'm a local rule-based demo assistant — try one of the suggestion chips for questions I can ground in real app data (waste, demand, NGOs, CO₂, sensors).<div class="sup">In production this endpoint proxies an LLM with tool access to the same data APIs.</div>`;
}